# See the mkdocs user guide for more information on these settings.
#   http://www.mkdocs.org/user-guide/configuration/

site_name:        DataStreams.jl
repo_url:         https://github.com/quinnj/DataStreams.jl
site_description: Source/Sink framework for data transfer in Julia
site_author:      Jacob Quinn

theme: material

extra_css:
  - assets/Documenter.css

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML
  - assets/mathjaxhelper.js

markdown_extensions:
  - codehilite
  - extra
  - tables
  - fenced_code
  - mdx_math
  - admonition

docs_dir: 'build'

pages:
  - Home: index.md
